apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: javawebapp
spec:
  containers:
    - name: first-container
      image: dockerhandson/java-web-app
      ports:
      - containerPort: 8080
